server:
  port: 8080

spring:
  cloud:
    gateway:
      default-filters:
        - name: LoggingFilter
      routes:
        - id: movieRoute
          uri: lb://movie-service
          predicates:
            - Path=/movies/**
          filters:
            - name: CircuitBreaker
              args:
                name: movieService
                fallbackUri: forward:/fallback/movies
        - id: catalogRoute
          uri: lb://catalog-service
          predicates:
            - Path=/catalogs/**
          filters:
            - name: CircuitBreaker
              args:
                name: catalogService
                fallbackUri: forward:/fallback/catalogs
        - id: seriesRoute
          uri: lb://serie-service
          predicates:
            - Path=/series/**
          filters:
            - name: CircuitBreaker
              args:
                name: serieService
                fallbackUri: forward:/fallback/serie

info:
  app:
    name: ${spring.application.name}
    version: 1.0.0
    description: Gateway Service
